// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/mymicro.proto

package mymicro

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Mymicro service

func NewMymicroEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Mymicro service

type MymicroService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Mymicro_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Mymicro_PingPongService, error)
}

type mymicroService struct {
	c    client.Client
	name string
}

func NewMymicroService(name string, c client.Client) MymicroService {
	return &mymicroService{
		c:    c,
		name: name,
	}
}

func (c *mymicroService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Mymicro.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mymicroService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Mymicro_StreamService, error) {
	req := c.c.NewRequest(c.name, "Mymicro.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &mymicroServiceStream{stream}, nil
}

type Mymicro_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type mymicroServiceStream struct {
	stream client.Stream
}

func (x *mymicroServiceStream) Close() error {
	return x.stream.Close()
}

func (x *mymicroServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mymicroServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mymicroServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mymicroServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mymicroService) PingPong(ctx context.Context, opts ...client.CallOption) (Mymicro_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Mymicro.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &mymicroServicePingPong{stream}, nil
}

type Mymicro_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type mymicroServicePingPong struct {
	stream client.Stream
}

func (x *mymicroServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *mymicroServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *mymicroServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mymicroServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mymicroServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *mymicroServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Mymicro service

type MymicroHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Mymicro_StreamStream) error
	PingPong(context.Context, Mymicro_PingPongStream) error
}

func RegisterMymicroHandler(s server.Server, hdlr MymicroHandler, opts ...server.HandlerOption) error {
	type mymicro interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Mymicro struct {
		mymicro
	}
	h := &mymicroHandler{hdlr}
	return s.Handle(s.NewHandler(&Mymicro{h}, opts...))
}

type mymicroHandler struct {
	MymicroHandler
}

func (h *mymicroHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MymicroHandler.Call(ctx, in, out)
}

func (h *mymicroHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MymicroHandler.Stream(ctx, m, &mymicroStreamStream{stream})
}

type Mymicro_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type mymicroStreamStream struct {
	stream server.Stream
}

func (x *mymicroStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mymicroStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mymicroStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mymicroStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mymicroStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *mymicroHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MymicroHandler.PingPong(ctx, &mymicroPingPongStream{stream})
}

type Mymicro_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type mymicroPingPongStream struct {
	stream server.Stream
}

func (x *mymicroPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *mymicroPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mymicroPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mymicroPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mymicroPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *mymicroPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
