// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: getimg.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` //传入
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` //传出
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getimg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_getimg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_getimg_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Test string `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
}

func (x *MTest) Reset() {
	*x = MTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getimg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTest) ProtoMessage() {}

func (x *MTest) ProtoReflect() protoreflect.Message {
	mi := &file_getimg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTest.ProtoReflect.Descriptor instead.
func (*MTest) Descriptor() ([]byte, []int) {
	return file_getimg_proto_rawDescGZIP(), []int{1}
}

func (x *MTest) GetTest() string {
	if x != nil {
		return x.Test
	}
	return ""
}

var File_getimg_proto protoreflect.FileDescriptor

var file_getimg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x65, 0x74, 0x69, 0x6d, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x67, 0x65, 0x74, 0x69, 0x6d, 0x67, 0x22, 0x31, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1c, 0x0a, 0x06, 0x4d, 0x5f, 0x74,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x73, 0x74, 0x32, 0x5e, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x69, 0x6d,
	0x67, 0x12, 0x2a, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0f, 0x2e, 0x67, 0x65, 0x74, 0x69,
	0x6d, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0f, 0x2e, 0x67, 0x65, 0x74,
	0x69, 0x6d, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x28, 0x0a,
	0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x2e, 0x67, 0x65, 0x74, 0x69, 0x6d, 0x67, 0x2e, 0x4d,
	0x5f, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x67, 0x65, 0x74, 0x69, 0x6d, 0x67, 0x2e, 0x4d,
	0x5f, 0x74, 0x65, 0x73, 0x74, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x3b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_getimg_proto_rawDescOnce sync.Once
	file_getimg_proto_rawDescData = file_getimg_proto_rawDesc
)

func file_getimg_proto_rawDescGZIP() []byte {
	file_getimg_proto_rawDescOnce.Do(func() {
		file_getimg_proto_rawDescData = protoimpl.X.CompressGZIP(file_getimg_proto_rawDescData)
	})
	return file_getimg_proto_rawDescData
}

var file_getimg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getimg_proto_goTypes = []interface{}{
	(*Message)(nil), // 0: getimg.Message
	(*MTest)(nil),   // 1: getimg.M_test
}
var file_getimg_proto_depIdxs = []int32{
	0, // 0: getimg.Getimg.Call:input_type -> getimg.Message
	1, // 1: getimg.Getimg.Test:input_type -> getimg.M_test
	0, // 2: getimg.Getimg.Call:output_type -> getimg.Message
	1, // 3: getimg.Getimg.Test:output_type -> getimg.M_test
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getimg_proto_init() }
func file_getimg_proto_init() {
	if File_getimg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getimg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getimg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getimg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getimg_proto_goTypes,
		DependencyIndexes: file_getimg_proto_depIdxs,
		MessageInfos:      file_getimg_proto_msgTypes,
	}.Build()
	File_getimg_proto = out.File
	file_getimg_proto_rawDesc = nil
	file_getimg_proto_goTypes = nil
	file_getimg_proto_depIdxs = nil
}
